apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lk1-poi-map-app-dev
  annotations:
    argocd/app-name: lk1-poi-map-app-dev
    backstage.io/kubernetes-id: lk1-poi-map-app
    backstage.io/kubernetes-namespace: lk1
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/lk1-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/lk1/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/lk1/deployments/lk1-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/lk1-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://lk1-poi-map-app-lk1.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/lkristie"
  system: workshop-system-lk1
  consumesApis:
    - gateway-api-lk1
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-lk1
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/lkristie"
